---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo
spec:
  entrypoint: main
  serviceAccountName: argo-server
  templates:
    - name: main
      steps:
        - - name: publish-container
            templateRef:
              name: cwft-kaniko-v2
              template: build-push
              clusterScope: true
            arguments:
              parameters:
                - name: appName
                  value: '{{workflow.parameters.appName}}'
                - name: branch
                  value: '{{workflow.parameters.branch}}'
                - name: containerRegistryURL
                  value: '{{workflow.parameters.containerRegistryURL}}'
                - name: gitUrlNoProtocol
                  value: '{{workflow.parameters.gitUrlNoProtocol}}'

        - - name: checkout
            templateRef:
              name: cwft-git-v2
              template: checkout-with-gitops
              clusterScope: true
            arguments:
              parameters:
                - name: appName
                  value: '{{workflow.parameters.appName}}'
                - name: branch
                  value: '{{workflow.parameters.branch}}'
                - name: gitUrlNoProtocol
                  value: '{{workflow.parameters.gitUrlNoProtocol}}'

        - - name: get-initial-chart-version
            templateRef:
              name: cwft-helm-v2
              template: get-chart-version
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.checkout.outputs.artifacts.repo-source}}'
              parameters:
                - name: appName
                  value: '{{workflow.parameters.appName}}'
                - name: chartDir
                  value: 'charts/{{workflow.parameters.appName}}'

        - - name: set-micro-chart-versions
            templateRef:
              name: cwft-helm-v2
              template: set-micro-chart-versions
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.checkout.outputs.artifacts.repo-source}}'
              parameters:
                - name: appName
                  value: '{{workflow.parameters.appName}}'
                - name: chartDir
                  value: 'charts/{{workflow.parameters.appName}}'
                - name: chartVersion
                  value: '{{steps.get-initial-chart-version.outputs.result}}'
                - name: shortSha
                  value: '{{workflow.parameters.shortSha}}'

        - - name: publish-micro-helm-chart
            templateRef:
              name: cwft-helm-v2
              template: publish-chart
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.set-micro-chart-versions.outputs.artifacts.repo-source}}'
              parameters:
                - name: appName
                  value: '{{workflow.parameters.appName}}'
                - name: chartDir
                  value: 'charts/{{workflow.parameters.appName}}'

        - - name: release-and-tag-main-with-notes
            templateRef:
              name: cwft-git-v2
              template: release-and-tag-main-with-notes
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.set-micro-chart-versions.outputs.artifacts.repo-source}}'
              parameters:
                - name: orgName
                  value: 'konstructio'
                - name: appName
                  value: '{{workflow.parameters.appName}}'
                - name: tagName
                  value: '{{steps.get-initial-chart-version.outputs.result}}'

        - - name: set-environment-version
            templateRef:
              name: cwft-helm-v2
              template: set-environment-version-for-macro-chart
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.set-micro-chart-versions.outputs.artifacts.repo-source}}'
              parameters:
                - name: fullChartPath
                  value: '{{workflow.parameters.gitopsDestinationFile}}'
                - name: chartVersion
                  value: '{{steps.get-initial-chart-version.outputs.result}}'
                - name: environment
                  value: '{{workflow.parameters.environment}}'

        - - name: commit-to-gitops
            templateRef:
              name: cwft-git-v2
              template: pull-commit-sign-push
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.set-environment-version.outputs.artifacts.repo-source}}'
              parameters:
                - name: repoName
                  value: 'gitops'
                - name: gitUrlNoProtocol
                  value: '{{workflow.parameters.gitUrlNoProtocol}}'
                - name: commitMessage
                  # Please, be careful updating this message, it must comply with:
                  # github skip ci rule: https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/
                  # github skip ci rule: https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs
                  # gitlab skip ci rule: https://devops.stackexchange.com/questions/6809/is-there-a-ci-skip-option-in-gitlab-ci
                  # in case, the rule is disbaled or don't work this step will create a circular trigger of builds and bumps of version.
                  value: "[skip ci] [CI SKIP] setting {{workflow.parameters.appName}} {{workflow.parameters.environment}} to chart version '{{steps.get-initial-chart-version.outputs.result}}'\n\nskip-checks:true"

        - - name: increment-chart-minor
            templateRef:
              name: cwft-helm-v2
              template: increment-chart-minor
              clusterScope: true
            arguments:
              artifacts:
                spec:
                  - name: chartDir
                    value: 'charts/{{workflow.parameters.appName}}'
                  - name: chartVersion
                    value: '{{steps.get-initial-chart-version.outputs.result}}'

        - - name: commit-to-app-repo
            templateRef:
              name: cwft-git-v2
              template: pull-commit-sign-push
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.set-environment-version.outputs.artifacts.repo-source}}'
              parameters:
                - name: repoName
                  value: '{{workflow.parameters.appName}}'
                - name: gitUrlNoProtocol
                  value: '{{workflow.parameters.gitUrlNoProtocol}}'
                - name: commitMessage
                  # Please, be careful updating this message, it must comply with:
                  # github skip ci rule: https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/
                  # github skip ci rule: https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs
                  # gitlab skip ci rule: https://devops.stackexchange.com/questions/6809/is-there-a-ci-skip-option-in-gitlab-ci
                  # in case, the rule is disbaled or don't work this step will create a circular trigger of builds and bumps of version.
                  value: "[skip ci] [CI SKIP] bumping chart after release'\n\nskip-checks:true"
