---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
spec:
  entrypoint: main
  serviceAccountName: argo-server
  templates:
    - name: main
      steps:
        - - name: publish-container
            templateRef:
              name: cwft-kaniko
              template: build-push
              clusterScope: true
            arguments:
              parameters:
                - name: appName
                  value: '{{workflow.parameters.appName}}'
                - name: branch
                  value: '{{workflow.parameters.branch}}'
                - name: containerRegistryURL
                  value: '{{workflow.parameters.containerRegistryURL}}'
                - name: gitUrlNoProtocol
                  value: '{{workflow.parameters.gitUrlNoProtocol}}'

        - - name: checkout
            templateRef:
              name: cwft-git
              template: checkout-with-gitops
              clusterScope: true
            arguments:
              parameters:
                - name: appName
                  value: '{{workflow.parameters.appName}}'
                - name: branch
                  value: '{{workflow.parameters.branch}}'
                - name: gitUrlNoProtocol
                  value: '{{workflow.parameters.gitUrlNoProtocol}}'

        - - name: get-initial-chart-version
            templateRef:
              name: cwft-helm
              template: get-chart-version
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.checkout.outputs.artifacts.repo-source}}'
              parameters:
                - name: appName
                  value: '{{workflow.parameters.appName}}'
                - name: chartDir
                  value: 'charts/{{workflow.parameters.appName}}'

        - - name: increment-chart-minor
            templateRef:
              name: cwft-helm
              template: increment-chart-minor
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.checkout.outputs.artifacts.repo-source}}'
              parameters:
                - name: appName
                  value: '{{workflow.parameters.appName}}'
                - name: chartDir
                  value: 'charts/{{workflow.parameters.appName}}'
                - name: chartVersion
                  value: '{{steps.get-initial-chart-version.outputs.result}}'

        - - name: get-updated-chart-version
            templateRef:
              name: cwft-helm
              template: get-chart-version
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.increment-chart-minor.outputs.artifacts.repo-source}}'
              parameters:
                - name: appName
                  value: '{{workflow.parameters.appName}}'
                - name: chartDir
                  value: 'charts/{{workflow.parameters.appName}}'

        - - name: set-chart-versions
            templateRef:
              name: cwft-helm
              template: set-chart-versions
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.increment-chart-minor.outputs.artifacts.repo-source}}'
              parameters:
                - name: appName
                  value: '{{workflow.parameters.appName}}'
                - name: chartDir
                  value: 'charts/{{workflow.parameters.appName}}'
                - name: chartVersion
                  value: '{{steps.get-updated-chart-version.outputs.result}}'
                - name: shortSha
                  value: '{{workflow.parameters.shortSha}}'

        - - name: publish-helm-chart
            templateRef:
              name: cwft-helm
              template: publish-chart
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.set-chart-versions.outputs.artifacts.repo-source}}'
              parameters:
                - name: appName
                  value: '{{workflow.parameters.appName}}'
                - name: chartDir
                  value: 'charts/{{workflow.parameters.appName}}'

        - - name: commit-chart-increment
            templateRef:
              name: cwft-git
              template: pull-commit-push
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.set-chart-versions.outputs.artifacts.repo-source}}'
              parameters:
                - name: repoName
                  value: '{{workflow.parameters.appName}}'
                - name: gitUrlNoProtocol
                  value: '{{workflow.parameters.gitUrlNoProtocol}}'
                - name: commitMessage
                  value: "setting {{workflow.parameters.appName}} {{workflow.parameters.environment}} to chart version {{steps.get-updated-chart-version.outputs.result}}"

        - - name: set-environment-version
            templateRef:
              name: cwft-helm
              template: set-environment-version
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.set-chart-versions.outputs.artifacts.repo-source}}'
              parameters:
                - name: fullChartPath
                  value: 'registry/{{workflow.parameters.clusterName}}/components/{{workflow.parameters.environment}}/{{workflow.parameters.appName}}/Chart.yaml'
                - name: chartVersion
                  value: '{{steps.get-updated-chart-version.outputs.result}}'
                - name: environment
                  value: '{{workflow.parameters.environment}}'

        - - name: commit-to-production
            templateRef:
              name: cwft-git
              template: pull-commit-push
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.set-environment-version.outputs.artifacts.repo-source}}'
              parameters:
                - name: repoName
                  value: 'gitops'
                - name: gitUrlNoProtocol
                  value: '{{workflow.parameters.gitUrlNoProtocol}}'
                - name: commitMessage
                  value: 'setting {{workflow.parameters.appName}} {{workflow.parameters.environment}} to chart version {{steps.get-updated-chart-version.outputs.result}}'
