---
name: Markdown Links Validation

on: [push, workflow_dispatch]

jobs:
  check-links:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout this repository
        uses: actions/checkout@v4.1.7

      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1.2.4
        with:
          github_token: ${{ secrets.github_token }}
          fail_on_error: true
          config_file: .linkinspector.yml
          filter_mode: nofilter
          reporter: github-pr-review
