name: Move assigned tasks to Fred in Notion
on:
  issues:
    types:
      - assigned
  workflow_dispatch:

jobs:
  add_to_notion:
    if: ${{ github.event.assignee.login == 'fharper' }}

    runs-on: ubuntu-latest
    steps:
    - name: Webhook
      uses: distributhor/workflow-webhook@v3
      env:
        webhook_url: ${{ secrets.NOTION_WEBHOOK_URL }}
        data: |
          {
            "issue": "${{ toJSON(github.event.issue.html_url) }}",
            "title": "${{ toJSON(github.event.issue.title) }}",
            "content": "${{ toJSON(github.event.issue.body) }}"
          }
